# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protocol.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='protocol.proto',
  package='mms',
  serialized_pb=_b('\n\x0eprotocol.proto\x12\x03mms\"`\n\x12TranscodeRequestPB\x12\x19\n\x11media_source_path\x18\x01 \x02(\t\x12\x1b\n\x13media_target_format\x18\x02 \x01(\t\x12\x12\n\nnotify_url\x18\x03 \x01(\t\"#\n\x13TranscodeResponsePB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"#\n\x13QueryStateRequestPB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"3\n\x14QueryStateResponsePB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\r\n\x05state\x18\x02 \x02(\t\"#\n\x13\x41\x63\x63\x65ssM3U8RequestPB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"$\n\x14\x41\x63\x63\x65ssM3U8ResponsePB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\"1\n\x12\x41\x63\x63\x65ssKeyRequestPB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\r\n\x05token\x18\x02 \x02(\t\"0\n\x13\x41\x63\x63\x65ssKeyResponsePB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x9d\x01\n\nTaskMetaPB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x11\n\tstate_str\x18\x02 \x02(\t\x12\x11\n\tstate_int\x18\x03 \x02(\x05\x12\x19\n\x11media_source_path\x18\x04 \x02(\t\x12\x15\n\rtarget_format\x18\x05 \x02(\t\x12\x11\n\tcreate_at\x18\x06 \x01(\t\x12\x16\n\x0elast_update_at\x18\x07 \x01(\t\"%\n\nMediaKeyPB\x12\x0b\n\x03key\x18\x01 \x02(\t\x12\n\n\x02iv\x18\x02 \x02(\t\"g\n\tHLSMetaPB\x12\x0c\n\x04uuid\x18\x01 \x02(\t\x12\x15\n\rgfs_m3u8_path\x18\x02 \x02(\t\x12\"\n\tmedia_key\x18\x03 \x02(\x0b\x32\x0f.mms.MediaKeyPB\x12\x11\n\tcreate_at\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TRANSCODEREQUESTPB = _descriptor.Descriptor(
  name='TranscodeRequestPB',
  full_name='mms.TranscodeRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='media_source_path', full_name='mms.TranscodeRequestPB.media_source_path', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_target_format', full_name='mms.TranscodeRequestPB.media_target_format', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notify_url', full_name='mms.TranscodeRequestPB.notify_url', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=119,
)


_TRANSCODERESPONSEPB = _descriptor.Descriptor(
  name='TranscodeResponsePB',
  full_name='mms.TranscodeResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.TranscodeResponsePB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=156,
)


_QUERYSTATEREQUESTPB = _descriptor.Descriptor(
  name='QueryStateRequestPB',
  full_name='mms.QueryStateRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.QueryStateRequestPB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=158,
  serialized_end=193,
)


_QUERYSTATERESPONSEPB = _descriptor.Descriptor(
  name='QueryStateResponsePB',
  full_name='mms.QueryStateResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.QueryStateResponsePB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state', full_name='mms.QueryStateResponsePB.state', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=195,
  serialized_end=246,
)


_ACCESSM3U8REQUESTPB = _descriptor.Descriptor(
  name='AccessM3U8RequestPB',
  full_name='mms.AccessM3U8RequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.AccessM3U8RequestPB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=248,
  serialized_end=283,
)


_ACCESSM3U8RESPONSEPB = _descriptor.Descriptor(
  name='AccessM3U8ResponsePB',
  full_name='mms.AccessM3U8ResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.AccessM3U8ResponsePB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=321,
)


_ACCESSKEYREQUESTPB = _descriptor.Descriptor(
  name='AccessKeyRequestPB',
  full_name='mms.AccessKeyRequestPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.AccessKeyRequestPB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='mms.AccessKeyRequestPB.token', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=372,
)


_ACCESSKEYRESPONSEPB = _descriptor.Descriptor(
  name='AccessKeyResponsePB',
  full_name='mms.AccessKeyResponsePB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.AccessKeyResponsePB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='key', full_name='mms.AccessKeyResponsePB.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=374,
  serialized_end=422,
)


_TASKMETAPB = _descriptor.Descriptor(
  name='TaskMetaPB',
  full_name='mms.TaskMetaPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.TaskMetaPB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_str', full_name='mms.TaskMetaPB.state_str', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='state_int', full_name='mms.TaskMetaPB.state_int', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_source_path', full_name='mms.TaskMetaPB.media_source_path', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='target_format', full_name='mms.TaskMetaPB.target_format', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_at', full_name='mms.TaskMetaPB.create_at', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='last_update_at', full_name='mms.TaskMetaPB.last_update_at', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=425,
  serialized_end=582,
)


_MEDIAKEYPB = _descriptor.Descriptor(
  name='MediaKeyPB',
  full_name='mms.MediaKeyPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mms.MediaKeyPB.key', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iv', full_name='mms.MediaKeyPB.iv', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=584,
  serialized_end=621,
)


_HLSMETAPB = _descriptor.Descriptor(
  name='HLSMetaPB',
  full_name='mms.HLSMetaPB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uuid', full_name='mms.HLSMetaPB.uuid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gfs_m3u8_path', full_name='mms.HLSMetaPB.gfs_m3u8_path', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='media_key', full_name='mms.HLSMetaPB.media_key', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_at', full_name='mms.HLSMetaPB.create_at', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=726,
)

_HLSMETAPB.fields_by_name['media_key'].message_type = _MEDIAKEYPB
DESCRIPTOR.message_types_by_name['TranscodeRequestPB'] = _TRANSCODEREQUESTPB
DESCRIPTOR.message_types_by_name['TranscodeResponsePB'] = _TRANSCODERESPONSEPB
DESCRIPTOR.message_types_by_name['QueryStateRequestPB'] = _QUERYSTATEREQUESTPB
DESCRIPTOR.message_types_by_name['QueryStateResponsePB'] = _QUERYSTATERESPONSEPB
DESCRIPTOR.message_types_by_name['AccessM3U8RequestPB'] = _ACCESSM3U8REQUESTPB
DESCRIPTOR.message_types_by_name['AccessM3U8ResponsePB'] = _ACCESSM3U8RESPONSEPB
DESCRIPTOR.message_types_by_name['AccessKeyRequestPB'] = _ACCESSKEYREQUESTPB
DESCRIPTOR.message_types_by_name['AccessKeyResponsePB'] = _ACCESSKEYRESPONSEPB
DESCRIPTOR.message_types_by_name['TaskMetaPB'] = _TASKMETAPB
DESCRIPTOR.message_types_by_name['MediaKeyPB'] = _MEDIAKEYPB
DESCRIPTOR.message_types_by_name['HLSMetaPB'] = _HLSMETAPB

TranscodeRequestPB = _reflection.GeneratedProtocolMessageType('TranscodeRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _TRANSCODEREQUESTPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.TranscodeRequestPB)
  ))
_sym_db.RegisterMessage(TranscodeRequestPB)

TranscodeResponsePB = _reflection.GeneratedProtocolMessageType('TranscodeResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _TRANSCODERESPONSEPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.TranscodeResponsePB)
  ))
_sym_db.RegisterMessage(TranscodeResponsePB)

QueryStateRequestPB = _reflection.GeneratedProtocolMessageType('QueryStateRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSTATEREQUESTPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.QueryStateRequestPB)
  ))
_sym_db.RegisterMessage(QueryStateRequestPB)

QueryStateResponsePB = _reflection.GeneratedProtocolMessageType('QueryStateResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _QUERYSTATERESPONSEPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.QueryStateResponsePB)
  ))
_sym_db.RegisterMessage(QueryStateResponsePB)

AccessM3U8RequestPB = _reflection.GeneratedProtocolMessageType('AccessM3U8RequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSM3U8REQUESTPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.AccessM3U8RequestPB)
  ))
_sym_db.RegisterMessage(AccessM3U8RequestPB)

AccessM3U8ResponsePB = _reflection.GeneratedProtocolMessageType('AccessM3U8ResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSM3U8RESPONSEPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.AccessM3U8ResponsePB)
  ))
_sym_db.RegisterMessage(AccessM3U8ResponsePB)

AccessKeyRequestPB = _reflection.GeneratedProtocolMessageType('AccessKeyRequestPB', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSKEYREQUESTPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.AccessKeyRequestPB)
  ))
_sym_db.RegisterMessage(AccessKeyRequestPB)

AccessKeyResponsePB = _reflection.GeneratedProtocolMessageType('AccessKeyResponsePB', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSKEYRESPONSEPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.AccessKeyResponsePB)
  ))
_sym_db.RegisterMessage(AccessKeyResponsePB)

TaskMetaPB = _reflection.GeneratedProtocolMessageType('TaskMetaPB', (_message.Message,), dict(
  DESCRIPTOR = _TASKMETAPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.TaskMetaPB)
  ))
_sym_db.RegisterMessage(TaskMetaPB)

MediaKeyPB = _reflection.GeneratedProtocolMessageType('MediaKeyPB', (_message.Message,), dict(
  DESCRIPTOR = _MEDIAKEYPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.MediaKeyPB)
  ))
_sym_db.RegisterMessage(MediaKeyPB)

HLSMetaPB = _reflection.GeneratedProtocolMessageType('HLSMetaPB', (_message.Message,), dict(
  DESCRIPTOR = _HLSMETAPB,
  __module__ = 'protocol_pb2'
  # @@protoc_insertion_point(class_scope:mms.HLSMetaPB)
  ))
_sym_db.RegisterMessage(HLSMetaPB)


# @@protoc_insertion_point(module_scope)
